# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Himbak
tagline:          'Life in Japan'
description:      "Personal blog about a foreigner's life in Japan."
url:              http://www.himbak.com/

author:
  name:           'Rowel del Rosario'
  url:            http://www.himbak.com/


plugins:
  - jekyll-paginate
paginate: 5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/roweldelrosario/roweldelrosario.github.io
