# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Himbak
tagline:          'Life in Japan'
description:      'Life in Japan'
url:              https://himbak.com
image:            'public/image/site.jpg'

author:
  name:           'Rowel del Rosario'
  url:            https://himbak.com


plugins:
  - jekyll-paginate
paginate: 5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/roweldelrosario/roweldelrosario.github.io
