# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            物語
tagline:          ''
description:      ''
url:              https://monogatari.himbak.com
image:            'public/image/site.jpg'

author:
  name:           'RJ1 del Rosario'
  url:            https://monogatari.himbak.com


plugins:
  - jekyll-paginate
paginate: 5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/rj1delrosario/monogatari
